export const LIST_ALL_ORDEM_SERVICOS = 'LIST_ALL_ORDEM_SERVICOS';
export const ADD_ORDEM_SERVICO = 'ADD_ORDEM_SERVICO';
export const EDIT_ORDEM_SERVICO = 'EDIT_ORDEM_SERVICO';
export const DELETE_ORDEM_SERVICO = 'DELETE_ORDEM_SERVICO';