export const LIST_ALL_ACESSORIOS = 'LIST_ALL_ACESSORIOS';
export const ADD_ACESSORIO = 'ADD_ACESSORIO';
export const EDIT_ACESSORIO = 'EDIT_ACESSORIO';
export const DELETE_ACESSORIO = 'DELETE_ACESSORIO';